export const ROUTES = {
    '/l/home': 'Home',
    '/l/products': 'Products',
    '/l/opportunities': 'Opportunities',
    '/l/about': 'About',
    '/l/contact': 'Contact',
    '/member/dashboard': 'Dashboard',
    '/member/income': 'Income',
    '/member/income/direct': 'Income',
    '/member/income/match': 'Income',
    '/member/income/indirect': 'Income',
    '/member/income/fifth': 'Income',
    '/member/income/unilevel': 'Income',
    '/member/income/stairstep': 'Income',    
    '/member/network': 'Network',
    '/member/network/genealogy': 'Network',
    '/member/network/linear': 'Network',
    '/member/network/directs': 'Network',
    '/member/network/indirects': 'Network',
    '/member/incentives': 'Incentives',
    '/member/codes/available': 'Codes',
    '/member/codes/sent': 'Codes',
    '/member/codes/used': 'Codes',
    '/member/feeds': 'News Feed',
    '/member/shop': 'Shop',
    '/member/ewallet': 'E-Wallet',    
    '/member/shopwallet': 'Shopping Wallet',
    '/member/leads': 'Leads'
}